### ISSUE TITLE
Update gtest dependency

### ISSUE THREAD

**Issue by chrisgilmerproj** [ros/homebrew-fuerte#5]
Homebrew no longer supports gtest on recommendation from google.  Please update the formula to reflect this.

**Comment by wjwwood** [comment]
Sorry, is there a conversation/issue/pull request on the homebrew repository that indicates this?

Either way we can completely remove gtest from this repository.

**Comment by wjwwood** [comment]
Also, gtest is not in this repository, are you suggesting we change something in one of the other formulae in this tap?

**Comment by wjwwood** [comment]
I updated the instructions in the README.md to point to ROS wiki, which is up-to-date.  Only thing related to gtest I could find in this repository.

**Comment by chrisgilmerproj** [comment]
Thanks for the quick response!  Yeah, I tried to install catkin and I got the dependency warning.  You can check it out: https://github.com/ros/homebrew-fuerte/blob/master/catkin.rb

**Comment by wjwwood** [comment]
This is actually not fixed yet.

**Comment by chrisgilmerproj** [comment]
I think we can get away with not using gtest, it just won't build the C++ test files.  Anyway, I appreciate you working on this.

**Comment by wjwwood** [comment]
https://github.com/ros/catkin/issues/157

**Comment by wjwwood** [comment]
Catkin actually fails to build without gtest, we need to integrate gtest or make it optional.

**Comment by wjwwood** [comment]
This has been fixed already in catkin, but there hasn't been a release yet.

**Comment by wjwwood** [comment]
Ok, I have it working on my system now, gtest is ignored for now.  I have asked about getting the gtest sources as a homebrew formula in the homebrew mailing list.  Closing this for now.

**Comment by chrisgilmerproj** [comment]
Thanks!

**Comment by chrisgilmerproj** [comment]
I found the old formula, or at least a version of it, here: https://github.com/mxcl/homebrew/blob/2bf506e3d90254f81a669a0216f33b2f09589028/Library/Formula/gtest.rb
