### ISSUE TITLE
Change URI from wg-debs to ros-gbp

### ISSUE THREAD

**Issue by NikolausDemmel** [ros/homebrew-fuerte#7]
The github URIs in the formulas are incorrect. They reference 'wg-debs', the correct repository seems to be https://github.com/ros-gbp/.

**Comment by jakewins** [comment]
+1 on this, this is a major hurdle when installing ROS on OS X. @wjwwood I'd be happy to update and provide a pull request, but I see that there are already year-old pending requests. Will you merge a PR if I provide one with updated repo paths?

**Comment by wjwwood** [comment]
Yes.

**Comment by clalancette** [comment]
Closing to archive this repository.
